server {
    listen 80;
    listen [::]:80;
    server_name safonov.gosha2016.fvds.ru;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/finance-acme;
    }

    location / {
        return 503 "HTTPS setup in progress\n";
    }
}
